version: '2'
services:

    ghost-buster:
        image: umputun/ghost-buster-docker
        build: build/ghost-buster
        restart: always
        container_name: ghost-buster

        environment:
            - BLOG_DOMAIN=http://p.umputun.com #<<-- EDIT THIS
            - NODE_ENV=production

        ports:
            - "2368:2368"
        volumes:
            - ./static:/ghost/static
            - ./data:/ghost-override
            - ./export.md:/export.md

    nginx:
        build: build/nginx
        restart: always
        container_name: ghost-nginx

        depends_on:
            - ghost-buster

        ports:
            - "80:80"

        volumes:
            - ./static:/ghost/static
            - ./logs:/var/log/nginx
